# Copyright (c) Facebook, Inc. and its affiliates.
from .maskformer_transformer_decoder import StandardTransformerDecoder
from .mask2former_transformer_decoder import MultiScaleMaskedTransformerDecoder
from .mask2former_transformer_decoder_zigzag import MultiScaleZigZagTransformerDecoder, MultiScaleZigZagInTransformerDecoder, MultiScaleMaskedZigZagTransformerDecoder
from .mask2former_transformer_decoder_direction import MultiScaleMaskedTransformerDecoderDirection
from .mask2former_transformer_decoder_decouple import MultiScaleMaskedTransformerDecoderDecouple
from .mask2former_transformer_decoder_decouple_class import MultiScaleMaskedTransformerDecoderDecoupleClass
from .mask2former_transformer_decoder_decouple_clsattention import MultiScaleMaskedTransformerDecoderDecoupleClsAttention
from .mask2former_transformer_decoder_selectquery import MultiScaleMaskedTransformerDecoderSelectQuery
from .mask2former_transformer_decoder_focal import MultiScaleMaskedTransformerDecoderFocal
from .mask2former_transformer_decoder_zigzagpixelembed import MultiScaleMaskedTransformerDecoderZigZagPE
from .mask2former_transformer_decoder_clsSA import MultiScaleMaskedTransformerDecoderClsSA
from .mask2former_transformer_decoder_replace_decouple_clsattention import MultiScaleMaskedTransformerDecoderReplaceDecoupleClsAttention
from .mask2former_transformer_decoder_iou import MultiScaleMaskedTransformerDecoderIou
from .mask2former_transformer_decoder_iou_decouple import MultiScaleMaskedTransformerDecoderIouDecouple
from .mask2former_transformer_decoder_iou_decouple_detach import MultiScaleMaskedTransformerDecoderIouDecoupleDetach
from .mask2former_transformer_decoder_alignmaskattention import MultiScaleMaskedTransformerDecoderAlignmaskAttention