# Copyright (c) Facebook, Inc. and its affiliates.
from .maskformer_transformer_decoder import StandardTransformerDecoder
from .mask2former_transformer_decoder import MultiScaleMaskedTransformerDecoder
from .mask2former_transformer_decoder_zigzag import MultiScaleZigZagTransformerDecoder, MultiScaleZigZagInTransformerDecoder, MultiScaleMaskedZigZagTransformerDecoder
from .mask2former_transformer_decoder_direction import MultiScaleMaskedTransformerDecoderDirection
from .mask2former_transformer_decoder_decouple import MultiScaleMaskedTransformerDecoderDecouple
from .mask2former_transformer_decoder_decouple_class import MultiScaleMaskedTransformerDecoderDecoupleClass
from .mask2former_transformer_decoder_decouple_clsattention import MultiScaleMaskedTransformerDecoderDecoupleClsAttention
from .mask2former_transformer_decoder_selectquery import MultiScaleMaskedTransformerDecoderSelectQuery

